[package]
name = "code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.3"
fast-float = "0.2.0"
fmmap = "0.3.3"
rustc-hash = "1.1.0"

[profile.release]
debug = true
